# Generated by Django 3.1.7 on 2021-03-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
