# Generated by Django 3.1.7 on 2021-03-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0002_auto_20210331_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userID',
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='user', max_length=20, unique=True),
        ),
    ]
