# Generated by Django 3.1.7 on 2021-04-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0003_auto_20210331_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='Workout',
        ),
    ]
