# Generated by Django 3.1.7 on 2021-04-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0004_auto_20210430_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('details', models.TextField()),
            ],
        ),
    ]
