# Generated by Django 3.1.7 on 2021-04-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0005_workout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('details', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
