# Generated by Django 3.1.7 on 2021-04-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0006_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=500, null=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
