# Generated by Django 3.1.7 on 2021-05-03 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthandfitness', '0007_auto_20210430_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
